name: Publish to Docker Hub

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_context: [".", alpine]
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Enable experimental Docker features
        run: "echo '{\"experimental\": true}' | sudo tee /etc/docker/daemon.json"

      - name: Restart Docker
        run: sudo service docker restart

      - name: Docker login
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD

      - name: Docker version
        run: docker version

      # - name: buildx help
      #   run: docker builder --help

      # - name: Enable buildx
      #   run: docker buildx create --use --name build

      - name: Build image
        run: >
          docker builder build \
            -t dnrce/thelounge:latest \
            --platform linux/amd64,linux/arm64 \
            --build-arg THELOUNGE_VERSION=4.1.0 \
            --file ${{ matrix.build_context }}/Dockerfile \
            --output type=image,push=true \
            .
